version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - database_url=postgres://user:password@postgres:5432/DB
    ports:
      - "1026:1026"
    volumes:
      - .:/app
    command: bash -c "poetry run python3 main.py"
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5434:5432"
